-- Self-serve trial link table.
-- Each row is a shareable /start/{token} URL that leads to a
-- 7-day Stripe trial checkout. One row per link generated by admin.
CREATE TABLE IF NOT EXISTS trial_links (
  id           UUID        NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  token        TEXT        NOT NULL UNIQUE,
  price_amount INTEGER     NOT NULL DEFAULT 3000,   -- pence, e.g. 3000 = £30/mo
  label        TEXT,                                -- admin note, e.g. "John Smith ref"
  status       TEXT        NOT NULL DEFAULT 'unused' CHECK (status IN ('unused', 'completed')),
  client_id    UUID        REFERENCES clients(id) ON DELETE SET NULL,  -- set once checkout is created
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
